### ISSUE TITLE
Duplicated reviewpad report

### ISSUE THREAD

**Issue by shay2025** [reviewpad/reviewpad#102]
**Describe the bug**
In this PR https://github.com/reviewpad/reviewpad/pull/101, it was generated 2 identical reviewpad reports.

**To Reproduce**
https://github.com/reviewpad/reviewpad/pull/101

**Expected behavior**
Only one reviewpad report should appear.

**Screenshots**
*None*

**Comment by marcelosousa** [comment]
I couldn't reproduce this issue. Closing for now.
