### ISSUE TITLE
Re-request review when reviewer has approved the review

### ISSUE THREAD

**Issue by shay2025** [reviewpad/reviewpad#212]
**Describe the bug**
When a reviewer approves a pull request, their review is being re-requested when reviewpad re-runs.

**To Reproduce**
See https://github.com/reviewpad/reviewpad/pull/192.

**Expected behavior**
When a reviewer has approved the review, reviewpad shouldn't re-request a review from that reviewer.

**Screenshots**
*None*

**Comment by versoul** [comment]
@marcelosousa @shay2025 @ferreiratiago  that is not replicable
