### ISSUE TITLE
built-in: lastEventAt

### ISSUE THREAD

**Issue by marcelosousa** [reviewpad/reviewpad#250]
**Is your feature request related to a problem? Please describe.**
In connection to #241, we need a built-in to get us the timestamp of the last event in a timeline of an issue/pull request.

**Describe the solution you'd like**
Check the specification at: https://github.com/reviewpad/docs/pull/22/files#diff-b8fe3742526782be6b0eade46eb19d2a10c209a29f40c534fc90e0f957523558

**Comment by shay2025** [comment]
@marcelosousa shouldn'this built-in be named `$updatedAt()` instead?
