### ISSUE TITLE
Add support for issues

### ISSUE THREAD

**Issue by marcelosousa** [reviewpad/reviewpad#258]
**Is your feature request related to a problem? Please describe.**
At the moment, the main function of Reviewpad in the runner.go (https://github.com/reviewpad/reviewpad/blob/main/runner.go#L38-L47) assumes that we will always run on a pull request.

This issue is to start evolving Reviewpad so that we can also support issues.

For that to happen, we need to receive in the runner, not a pull request but a `TargetEntity` object (https://github.com/reviewpad/host-event-handler/blob/main/handler/processors.go#L25-L27).

This will require also changing both environments:

1. Engine environment (https://github.com/reviewpad/reviewpad/blob/main/engine/env.go#L42)
2. Aladino execution environment (https://github.com/reviewpad/reviewpad/blob/main/lang/aladino/env.go#L47-L48).

We will also need to change:

1. Aladino interpreter for EvalExpr (https://github.com/reviewpad/reviewpad/blob/main/lang/aladino/interpreter.go#L94) such that it takes into account the kind of the rule to understand if it should be evaluated or not. For example, a rule with `kind: patch` assumes that the `TargetEntity` *is* a pull request. Otherwise, it could be either a pull request or an issue.

**Comment by zolamk** [comment]
@marcelosousa I think we might also need to add the `owner` and `repo` information to `TargetEntity` object, because before we used to get that information in reviewpad from the pull request, what do you think?
