### ISSUE TITLE
YAML property to define failure mode

### ISSUE THREAD

**Issue by marcelosousa** [reviewpad/reviewpad#28]
**Is your feature request related to a problem? Please describe.**
Although the engine runners return an error, this error is at the moment ignored by the runner users such as the [Reviewpad Action](https://github.com/reviewpad/action). It should be up to the user to specify if that is the intended behaviour.

**Describe the solution you'd like**
Introduce a new boolean property in the YAML called "fail-on-error" which is `true` by default.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by shay2025** [comment]
I propose this property has the inverse logic, i.e, "skip-fail-on-error" which is `false` by default.
This because the default value of "fail-on-error", since it is a boolean, will always be `false`.
A way to contour this is to use pointers which isn't a very neat possibility.

**Comment by shay2025** [comment]
I was decided this property would be names `ignore-errors`.
