### ISSUE TITLE
Add `extends` system to Engine

### ISSUE THREAD

**Issue by marcelosousa** [reviewpad/reviewpad#306]
**Is your feature request related to a problem? Please describe.**
Reviewpad already has a basic import loader mechanism but it is quite painful to use because it requires a downloadable link. 

**Describe the solution you'd like**
First, I believe that what we want is an `extends` directive instead of an `import`. This is because want to also execute the workflows from the base files.

The extends directive should allow to reference relative and global links in the style of `go`.

**Additional context**
We will have to adapt some linter rules to be more flexible in such that it doesn't complain if rules are unused. We could run the linter in different modes.

**Comment by Riscky** [comment]
We (Channable) would love to see this, as we currently have a lot of duplicated rules across repositories.

**Comment by marcelosousa** [comment]
Hi @Riscky - thanks for the feedback! 

Just to clarify, we already have a basic import mechanism, you can see an example here:
https://github.com/reviewpad/reviewpad/blob/main/reviewpad.yml#L4

This issue is to improve the current system so that we don't have to add raw GH urls and also to make it more useful.

**Comment by Riscky** [comment]
> we already have a basic import mechanism

We are aware, but we decided against using the URL imports, since it requires putting the shared configuration files behind a publicly accessible URL.

**Comment by marcelosousa** [comment]
> > we already have a basic import mechanism
> 
> We are aware, but we decided against using the URL imports, since it requires putting the shared configuration files behind a publicly accessible URL.

Makes sense - thanks for the feedback!
