### ISSUE TITLE
CI appears as skipped

### ISSUE THREAD

**Issue by ferreiratiago** [reviewpad/reviewpad#326]
**Describe the bug**
It can happen that CI is triggered more than once by reviewpad. When this happens, the first CI workflow runs but all the other are `skipped`. 

This is a problem because only the last CI status appears on the pull request. If the last status is `skipped`, then it will appear `skipped`.  This disable the ability to know **exactly** what the CI status is.

Here's an example, where Reviewpad triggers the CI 2 times:
- **Time A**: CI run and is **FAIL**
- **Time A+X**: CI runs and is **skipped** (this can happen for several reasons, see [details](https://github.com/reviewpad/reviewpad/blob/main/.github/workflows/pull_request_build.yml#L12))

In the pull request we will see the status `skipped` when the real status is `FAIL`.

**To Reproduce**
Here's an pr example here this happened:
https://github.com/reviewpad/reviewpad/pull/301/checks

**Expected behavior**
We should be able to see the CI status that really matters.

**Screenshots**

**Comment by marcelosousa** [comment]
It will be solved in version v4.x

**Comment by marcelosousa** [comment]
Closing this issue as it is not relevant anymore.
