### ISSUE TITLE
add label descriptions also if label is already created

### ISSUE THREAD

**Issue by schmelto** [reviewpad/reviewpad#334]
when a label is already created the action should update the description of the label.
Currently when the label is persistent in the repository and the action also has a description value for size labels those descriptions would not be updated.

I would consider using a workflow like this:
```mermaid
graph LR
    A[Label] --> C{has description?}
    C -->|yes| D[dont modify description]
    C -->|no| E[modify description]
```

**Comment by ferreiratiago** [comment]
Hi @schmelto Thanks for the feedback 🙏🏼 It makes total sense. A label description should be updated if updated on the reviewpad configuration.
