### ISSUE TITLE
Remove error return type in `GetLabels()`

### ISSUE THREAD

**Issue by shay2025** [reviewpad/reviewpad#338]
**Is your feature request related to a problem? Please describe.**
The `GetLabels` functions in https://github.com/reviewpad/reviewpad/blob/main/codehost/github/target/issue_target.go and https://github.com/reviewpad/reviewpad/blob/main/codehost/github/target/pull_request_target.go return the labels applied to one of this entities.

It is also declared in the signature that, besides returning the labels, it can return an error. 

However, this error is always `nil`.

**Describe the solution you'd like**
Update the `GetLabels()` signature from `GetLabels() ([]*Label, error)` to be `GetLabels() []*Label` and propagate this change to all places where this functions is used.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by michaelc0n** [comment]
i'd like to take this one 👍🏽

**Comment by shay2025** [comment]
Hi @michaelc0n Thanks for your help 🙏🏼 Check our [contribuition guidelines](https://docs.reviewpad.com/contributing/how-to-contribute) and go for it :smiley:

**Comment by shay2025** [comment]
Fixed by #393
