### ISSUE TITLE
running tests results in panic: interface conversion: interface {} is *git.GitError, not string

### ISSUE THREAD

**Issue by zolamk** [reviewpad/reviewpad#402]
**Describe the bug**
Running `task check -f` or `go test ./...` seems to result in `panic: interface conversion: interface {} is *git.GitError, not string` error

**Expected behavior**
Tests should succeed

**Screenshots**
![image](https://user-images.githubusercontent.com/14203663/196044522-00f268d9-d7cb-40d6-8f8e-90af4a026985.png)

**Comment by shay2025** [comment]
Related to #437
