### ISSUE TITLE
Duplicate report comment

### ISSUE THREAD

**Issue by ferreiratiago** [reviewpad/reviewpad#416]
**Describe the bug**
It can happen that reviewpad does the report comment more than once.

**To Reproduce**
- Open a pr 
- Make a review
- See the report appearing more than once
(please note that this issue may not be easy to replicate)

**Expected behavior**
Reviewpad should only make the report comment once.

**Screenshots**
This issue can be seen in the pull request https://github.com/reviewpad/reviewpad/pull/412

<img width="1032" alt="Screen Shot 2022-10-24 at 8 49 03 PM" src="https://user-images.githubusercontent.com/3806676/197616021-e62d1a62-8ea0-4df0-b444-d0a2771b6512.png">

**Comment by zolamk** [comment]
I believe this issue might just be a glitch in `Github` because if we run the following GraphQL query to get the timeline items for the `ISSUE_COMMENT` and `COMMENT_DELETED_EVENT` we should see the duplicate reports `ISSUE_COMMENT` event or `COMMENT_DELETED_EVENT` if the report was sent twice and deleted

## Query 
```
query {
  repository(owner: "reviewpad", name: "reviewpad") {
    nameWithOwner
    pullRequest(number: 412) {
      number
      timelineItems(last: 100, itemTypes: [ISSUE_COMMENT, COMMENT_DELETED_EVENT]) {
        nodes {
          __typename
          ... on IssueComment {
            body
          }
          ... on CommentDeletedEvent {
            deletedCommentAuthor {
              login
            }
          }
        }
      }
    }
  }
}
```

## Result
```
{
  "data": {
    "repository": {
      "nameWithOwner": "reviewpad/reviewpad",
      "pullRequest": {
        "number": 412,
        "timelineItems": {
          "nodes": [
            {
              "__typename": "IssueComment",
              "body": "<!--@annotation-reviewpad-report-->\n**Reviewpad Report**\n\n**:information_source: Messages**\n* If you are adding or updating a built-in, please do not forget to update the [docs](https://github.com/reviewpad/docs)\n\n"
            }
          ]
        }
      }
    }
  }
}
```

but as we can see in the result, there is a single `ISSUE_COMMENT` event and no `COMMENT_DELETED_EVENT`

**Comment by zolamk** [comment]
What do you think @ferreiratiago

**Comment by ferreiratiago** [comment]
You're right @zolamk It's hard to understand what happened. Maybe it was indeed a github glitch. Let's close the issue for now. Thanks 🙏
