### ISSUE TITLE
Create builtin to extract check status

### ISSUE THREAD

**Issue by ferreiratiago** [reviewpad/reviewpad#435]
**Is your feature request related to a problem? Please describe.**
Currently, reviewpad does not have the ability to extract a check status for [check run](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#check_run) and [check suite](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#check_suite).

We need to add the ability to fetch the status for a check run and check suite.

**Describe the solution you'd like**
First, we need to understand the difference between a check run and a check suite. Then, evaluate if both built-ins are required and what are the possible status a check run/suite can return.

After getting all this info we need to implement the required builtins in order to fetch the check run/suite status.

Proposed solutions:
```yml
$checkRunStatus(<RUN_NAME>)
$checkSuiteStatus(<SUITE_NAME>)
```

**Comment by shay2025** [comment]
@ferreiratiago lookint at the implementation of the built-in `$workflowStatus`, it seems to be the same as it would be for `$checkRunStatus(<RUN_NAME>)`, does it not?
https://github.com/reviewpad/reviewpad/blob/main/plugins/aladino/functions/workflowStatus.go

**Comment by shay2025** [comment]
A check run can have one of the following status: `queued`, `in_progress`, `completed` (https://docs.github.com/en/rest/guides/getting-started-with-the-checks-api#about-check-runs).
While a check suite, which is a set of check runs, summarize the status and conclusion of the check runs that a suite includes.

**Comment by shay2025** [comment]
It would make sense to have two built-ins one that checks the status of a `check run` and another that checks the status of a `check suite`. This because we may only want to know the status of an individual check since a check suite may contain more than one check run.

**Comment by shay2025** [comment]
I don't know if it is possible to get a check suite by name since the github check suite object does not contain any field with the name https://docs.github.com/en/rest/checks/suites#get-a-check-suite
