### ISSUE TITLE
built-in $removeAllLabels()

### ISSUE THREAD

**Issue by marcelosousa** [reviewpad/reviewpad#436]
**Is your feature request related to a problem? Please describe.**
In many situations, we would like to simply remove all the labels currently assigned to the pull request.

**Describe the solution you'd like**
A built-in $removeAllLabels() which doesn't take any arguments and removes all the labels associated to the pull request.

**Comment by shay2025** [comment]
Is this built-in really necessary? This can already be done by doing: `$removeLabels($labels())`.

**Comment by shay2025** [comment]
Suggestion by @ferreiratiago: remove all labels defined within `reviewpad.yml`.

**Comment by marcelosousa** [comment]
I agree that this issue is not relevant as it is possible do it using current built-ins.
