### ISSUE TITLE
$status() builtin to query the status of an issue/PR

### ISSUE THREAD

**Issue by adrianoapmartins** [reviewpad/reviewpad#444]
Built-in that returns the status of an issue or PR.
It will allow for interesting automation within projects. When trying to build a workflow to automatically move issues in a project we need to access their status (open/closed).

Usecase 1: when an issue is created, add it to the project backlog (for this this one I don't think this builtin is particularly needed)
Usecase 2: when an issue is closed, add it to the done lane in the project

**Comment by adrianoapmartins** [comment]
@shay2025, can you help here?

**Comment by shay2025** [comment]
@adrianoapmartins we already have this workflow, as soon as an issue is created it will be put in the Backlog and as soon as it is done it is put on the Done column

**Comment by shay2025** [comment]
We may not have it for the usecase 2 that you mentioned but maybe instead of having a `$status` built-in, it could be a `$isClosed` built-in.

**Comment by adrianoapmartins** [comment]
Awesome, @shay2025, but where's the part of the workflow for 
> and as soon as it is done it is put on the Done column.

?

**Comment by shay2025** [comment]
I responded to that on the previous comment: https://github.com/reviewpad/reviewpad/issues/444#issuecomment-1311572375

**Comment by marcelosousa** [comment]
@adrianoapmartins with github projects you can already setup these automations as workflows:

<img width="1781" alt="Screenshot 2022-11-24 at 16 03 09" src="https://user-images.githubusercontent.com/601882/203815168-520d0e4c-fb03-439a-b88b-e98a7e5118e6.png">
