### ISSUE TITLE
Add function to set a project field

### ISSUE THREAD

**Issue by nhuray** [reviewpad/reviewpad#494]
**Is your feature request related to a problem? Please describe.**

[Github projects](https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/about-projects) allow to create boards to triage pull requests.  

ReviewPad already support the function [addProject](https://docs.reviewpad.com/next/guides/built-ins#addtoproject) allowing to add or update a pull request to a Github project with a specific status. 

**Describe the solution you'd like**

In order to have more triage capability it would be nice to implement a `setProjectField` function to add or update a project field. 

For instance we would be able to create a `Size` field to triage pull request by size. 

**Describe alternatives you've considered**

The workaround at the moment is to set a label on the pull request and to have a github action workflow parse that label and create  or update the project field.

Here is an action that can be used for that: https://github.com/austenstone/project-update

**Comment by marcelosousa** [comment]
Thanks for this issue @nhuray. I suppose the best way to deal with this would be to have a project fields sections in the Reviewpad YML configuration (similarly to what we have with the labels) that would create/updates the fields so that they could be used later on. WDYT?

**Comment by nhuray** [comment]
HI @marcelosousa I think we can implement that in 2 steps: 
  - **Step 1**: add an action `setProjectField` setting the field value BUT the field needs to exists otherwise reviewpad will trigger an error
  - **Step2**: create fields from Reviewpad with values.

# Step 1 specification

For step 1, we might have something like:

**Description**:

Set the value of an existing project field.

If the **project** doesn't exist, an error is returned.
If the **field** doesn't exist, an error is returned.

**Parameters**:

| Parameter       | Type    | Description                                              |
| :-------------- | :------ | :------------------------------------------------------- |
| `project_title` | string  | The title of the project  - case sensitive (must exists).             |
| `field_name`   | string  | The name of the project field (must exists). |
| `field_value`   | string  | The value of the project field. |

**Examples**:

```yml
$setProjectField("reviewpad", "Size", "small")
```

# Step 2 specification

For step 2, we might have something like:


```yml
api-version: reviewpad.com/v3.x

project-fields:
   'Size':
      - 'small'
      - 'medium'
      - 'large'
```

The fields will be created prior to run workflows or pipelines.

**Comment by nhuray** [comment]
@marcelosousa what do you think ?

**Comment by marcelosousa** [comment]
@nhuray make sense to me. Adding to this week's planning!

**Comment by nhuray** [comment]
@marcelosousa I'm not a Go developer myself, but let me know if I can help !

**Comment by marcelosousa** [comment]
@nhuray a first functional increment of this issue is already in #551 that supports this built-in for single select fields. 

In your use case, is it a must have to support other types of fields (e.g. `text`, `number` or `iteration` fields)?

**Comment by nhuray** [comment]
@marcelosousa for my use case I would like mostly to support `text` fields (e.g `Size: small`) 

I suppose `text` and `number` are the most important to implement. I don't see use cases for `iterations` fields at the moment.

Thanks for your work on that issue ❤️

**Comment by marcelosousa** [comment]
@nhuray thanks for this feedback - this is already done in https://github.com/reviewpad/reviewpad/pull/551 so this issue will also be closed by that. Feel free to open more issues with other built-ins that could be useful for you and we hope to get feedback about this built-in that should be shipped tomorrow!

**Comment by nhuray** [comment]
@marcelosousa Thanks so much for your work on that issue. 

I would be more than happy to give feedback about our usage in couple of weeks.
