### ISSUE TITLE
Output triggered rules and the set of actions executed per rule

### ISSUE THREAD

**Issue by shay2025** [reviewpad/reviewpad#516]
Currently, reviewpad outputs the executed program which consists of a set of executed actions.
Right now, it is needed for reviewpad to output the rules that are triggered and the set of actions executed per rule.
```
[
    {
      rule: RULE_1_NAME,
      actions: [ACTION_1_1, ACTION_1_2, ..., ACTION_1_N]
    },
    {
      rule: RULE_2_NAME,
      actions: [ACTION_2_1, ACTION_2_2, ..., ACTION_2_N]
    },
]
```

**Comment by ferreiratiago** [comment]
Not applicable for now. Closing.
