### ISSUE TITLE
Add logging information for overrides

### ISSUE THREAD

**Issue by marcelosousa** [reviewpad/reviewpad#517]
**Is your feature request related to a problem? Please describe.**
In connection with #306 and #515, we need to add logging information to notify users that labels, groups, rules, workflows or pipelines were overridden.

**Comment by ferreiratiago** [comment]
As discussed we will break this issue into small increments:

Take the following configurations as example:

Configuration A
```yml
label:
  - name: hello
```

Configuration B
```yml
extends:
   - path/to/Configuration A
label:
  - name: hello
```

- [ ] Logger when an overwrite happens (e.g. label `hello` is being overwritten)

- [ ] Understand how hard it is to say the path from which the initial value is being overwritten, (e.g. label `hello` is being overwritten after extending `path/to/Configuration A`)

For now, we will not share this info with the user. For that, we will first define a strategy to properly share reviewpad execution with the user.
