### ISSUE TITLE
Label color not updated when modifying label spec

### ISSUE THREAD

**Issue by tiithansen** [reviewpad/reviewpad#530]
**Describe the bug**
1. Create label without setting color
2. Add label to PR (grayish color by default)
3. Modify label and add color and description.
4. Add label to PR - color not changed, description changed.

**Expected behavior**
Color is also updated

**Comment by marcelosousa** [comment]
Just to clarify the scenario @tiithansen, in step 3, the modification was done manually or through the Reviewpad specification?

**Comment by marcelosousa** [comment]
Thanks @tiithansen ! I will send a fix shortly. Please note that this is not immediately released into the action after the fix reaches the main branch. We'll do a release later today so that you can get the latest batch of improvements!
