### ISSUE TITLE
Add `service` and `payload` parameters to mixpanel collector

### ISSUE THREAD

**Issue by shay2025** [reviewpad/reviewpad#539]
**Is your feature request related to a problem? Please describe.**
Mixpanel helps track the errors that occur on the engine. But we don't have a way to know which service the error comes from or the payload.

**Describe the solution you'd like**
Add a `service` parameter to the collector which helps identify which service the collector is related to (e.g., `entry_gate`, `event_handler`, `engine`) and a `payload` parameter.

**Comment by ferreiratiago** [comment]
The property service was added. We will skip the payload for now.
