### ISSUE TITLE
Reviewpad moves project card items unexpectedly

### ISSUE THREAD

**Issue by shay2025** [reviewpad/reviewpad#578]
**Describe the bug**
Reviewpad when running changes the card items' positions around the columns of a project unexpectedly which is frustrating.

**Expected behavior**
The cards should move accordingly.

**Comment by marcelosousa** [comment]
In the reviewpad configuration, we were always adding the issue or pull request to a particular column even if the entity was already in the project (and possibly in another lane).

Fixed by [43cad8e](https://github.com/reviewpad/reviewpad/commit/43cad8e1ec5a7f77bb0a9e076ddc596387147016)
