### ISSUE TITLE
Identify which builtins are failing like review builtin

### ISSUE THREAD

**Issue by ferreiratiago** [reviewpad/reviewpad#598]
As discussed with @shay2025 there are more built-ins that may be failing like the review builtin.

The idea of this issue is to identify which built-ins are failing for the same reasons that the [review built-in was failing](https://github.com/reviewpad/reviewpad/issues/567) and create an issue to address those built-ins.

**Comment by shay2025** [comment]
The following built-ins are failing on the GitHub App but are working on the GitHub Action.
| **ACTION** | **ERROR** |
| --- | --- |
| `$close` | 422 Validation Failed [{Resource:PullRequest Field:maintainer_can_modify Code:invalid Message:Only the pull request author may change the maintainer_can_modify value}] | 
| `$triggerWorkflow` | `403 Resource not accessible by integration []` when trying to add this workflow https://docs.github.com/en/actions/managing-issues-and-pull-requests/adding-labels-to-issues#creating-the-workflow replacing the `on` field with `workflow_dispatch` as said in https://docs.reviewpad.com/guides/built-ins#triggerworkflow |
