### ISSUE TITLE
Improve rebase

### ISSUE THREAD

**Issue by ferreiratiago** [reviewpad/reviewpad#632]
**Is your feature request related to a problem? Please describe.**
It's not clear if the built-in rebase works in all scenarios:
- [ ] GitHub Action
   - [ ] Fork
   - [ ] Non-fork
   - [ ] Repository own
   - [ ] Repository collaborator
- [ ] GitHub App
   - [ ] Fork
   - [ ] Non-fork

**Describe the solution you'd like**
Investigate if the rebase built-in is working in all the scenarios and fix those which is not working properly.

**Additional context**
A conclusion from the investigation should be added as a comment on this issue.

**Comment by zolamk** [comment]
### Results

- [ ] GitHub Action
   - [ ] Fork
   - [ ] Non-fork
   - [ ] Repository own
   - [ ] Repository collaborator
- [ ] GitHub App
   - [ ] Fork
   - [ ] Non-fork - error `remote authentication required but no callback set`
