### ISSUE TITLE
Define built-in totalCodeReviewsInOrganization

### ISSUE THREAD

**Issue by ferreiratiago** [reviewpad/reviewpad#701]
## Context
We should be able to know the total number of code reviews a user has within the organization. Currently, the built-in `totalCodeReviews` only provides the total amount of code reviews within a repository.

## Proposed Solution
Define the built-in `totalCodeReviewsInOrganization` that gets the total number of open code reviews a user has created within an organization.

The organization is the one where the built-in is running.

The total number of code reviews should only count those that are open.

### Parameters

| Parameter | Type | Description |
| --- | --- | --- |
| `user_login` | string | The GitHub user login. |

### Example
`$totalCodeReviewsInOrganization("peter")`

**Comment by shay2025** [comment]
@ferreiratiago I would suggest we rename this built-in to one of the following:
- totalReviewsByUserInOtherRepositories
- getReviewCountForUserInOtherRepositories
- getUserPullRequestReviewCountInOtherRepos

**Comment by ferreiratiago** [comment]
This issue was badly specified.
