### ISSUE TITLE
The $setProjectField built-in should add the PR/Issue to the project if it's not already the case

### ISSUE THREAD

**Issue by fmallet** [reviewpad/reviewpad#782]
Today, the `$setProjectField()` built-in fails if the PR/Issue is not already added to the targeted project. So it's up to the user to make sure the PR/Issue is added to the project by calling first the `$addToProject()` built-in:

```
- $addToProject("Reviewpad", "Backlog")
- $setProjectField("Reviewpad", "Area", "Content")
```
To improve the Developer eXperience, the `$setProjectField()` should first add the PR/Issue to the project before setting the project field.

**Comment by shay2025** [comment]
@fmallet the `$addProject` built-in adds the issue/pull request in context to a project X at column Y (X and Y are arguments to the built-in). The `$setProjectField` sets the value of a GitHub project's [custom field](https://docs.github.com/en/issues/planning-and-tracking-with-projects/understanding-fields) for the pull request / issue in the current context.

If it is not already in the project, we want to add an issue / pull request to a project. However, to do this we need to specify at which column the issue/pull request should be added. What should be done in this case? Should we add a new parameter to the `$setProjectField` built-in or should we, by default, add the issue/pull request to the first column of the project?

**Comment by shay2025** [comment]
On Friday, June 9th, it was discussed with @ferreiratiago and @fmallet that the names of `$theProjectField` and `$addToProject` were misleading. `$addToProject` built-in does more than its name implies (the built-in adds the issue/PR to the project AND sets its status to a specified value). `$setProjectField` implies that we are changing a field in the project itself and not only changing a field value in the issue/PR in context.

Besides this, it was discussed that the built-in `$addToProject` should maybe be deprecated and a new built-in should emerge with the only functionality of adding the issue/PR to a project.

The `$setProjectField` functionality should remain the same.

We should come back to this in the future.
