### ISSUE TITLE
Reviewpad is merging ship PRs before the build is complete

### ISSUE THREAD

**Issue by marcelosousa** [reviewpad/reviewpad#815]
## Describe the bug

Reviewpad should wait before the build is green to merge a ship PR.

However, it is saying that the build is green when it is not and merging before hand.

## How to reproduce

Open a ship PR on this repository.

## Screenshots

![Screenshot 2023-04-05 at 10 41 05](https://user-images.githubusercontent.com/601882/230044121-0bb16fe4-b361-4e48-8662-039dbdf8594c.png)

**Comment by ferreiratiago** [comment]
This problem was due a to bad configuration.
