### ISSUE TITLE
reviewpad is not ignoring the checks

### ISSUE THREAD

**Issue by marcelosousa** [reviewpad/reviewpad#902]
## Describe the bug

In the following PR: https://github.com/reviewpad/reviewpad/pull/901, according to https://github.com/reviewpad/.github/blob/main/reviewpad-models/common.yml#LL164C45-L164C51, Reviewpad should ignore the qodana check and eventually merge automatically.

**Comment by ferreiratiago** [comment]
This issue was due to a bad configuration on `reviewpad.yml`.
